# Generated by Django 5.1.5 on 2025-02-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfect_Nannies_App', '0002_alter_nanny_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanny',
            name='charge',
        ),
        migrations.AlterField(
            model_name='guardian',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
